#
# Example VSCode rest client domain HTTP calls
#

@baseUrl = http://nuke:8080

@driver = qemu
@hypervisor = system

# @poolName = lab
# @poolUUID = 
# <uuid>{{poolUUID}}</uuid>
@poolPath = /lab/

@volume1Name = naslab-boot.img
# @volume1Path = /lab/naslab-boot.img
# @volume1Size = 50

@volume2Name = naslab-pool.img
# @volume2Path = /lab/naslab-pool.img
# @volume2Size = 50

@domainName = naslab
# @domainUUID = 
# <uuid>{{domainUUID}}</uuid>
@domainMem = 8

# @domainVolume1 = /lab/naslab-boot.img
# @domainVolume2 = /lab/naslab-pool.img
@domainInstallISO = /lab/TrueNAS-SCALE-22.02.0.iso
@domainNetworkMac = 

@networkName = br0
@networkBridge = br0

@vncHost = 0.0.0.0
@vncPort = 5900



###
# @name getAllDomains
GET {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain HTTP/1.1
Content-Type: application/json

{}



###
# @name createDomain
POST {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain HTTP/1.1
Content-Type: application/xml

<domain type="kvm">
  <name>{{domainName}}</name>
  <currentMemory unit="G">{{domainMem}}</currentMemory>
  <memory unit="G">{{domainMem}}</memory>
  <os>
    <type arch='x86_64'>hvm</type>
    <boot dev="hd"/>
    <boot dev="cdrom"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <vcpu>2</vcpu>
  <devices>
    <disk type="file" device="disk">
      <driver name="qemu" type="raw"/>
      <source file="{{poolPath}}/{{volume1Name}}"/>
      <target dev="vda" bus="virtio"/>
    </disk>
    <disk type="file" device="disk">
      <driver name="qemu" type="raw"/>
      <source file="{{poolPath}}/{{volume2Name}}"/>
      <target dev="vdb" bus="virtio"/>
    </disk>
    <disk type="file" device="cdrom">
      <source file="{{domainInstallISO}}"/>
      <target dev="hdc" bus="ide"/>
      <readonly/>
    </disk>
    <interface type="bridge">
      <source network="{{networkName}}" bridge="{{networkBridge}}"/>
      <mac address="{{domainNetworkMac}}"/>
      <target dev='vnet0'/>
      <model type='virtio'/>
      <alias name='net0'/>
    </interface>
    <input type="tablet" bus="usb">
      <alias name="input0"/>
      <address type="usb" bus="0" port="1"/>
    </input>
    <input type="mouse" bus="ps2">
      <alias name="input1"/>
    </input>
    <input type="keyboard" bus="ps2">
      <alias name="input2"/>
    </input>
    <graphics type="vnc" port="{{vncPort}}" autoport="no" listen="{{vncHost}}">
      <listen type="address" address="{{vncHost}}"/>
    </graphics>
    <console type="pty"/>
    <video>
      <model type="cirrus"/>
    </video>
  </devices>
</domain>



###
# @name getDomain
GET {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain/{{domainName}} HTTP/1.1
Content-Type: application/json

{}



###
# @name startDomain
PUT {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain/{{domainName}} HTTP/1.1
Content-Type: application/json

{
  "active": 1, 
  "autostart": 1
}



###
# @name stopDomain
PUT {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain/{{domainName}} HTTP/1.1
Content-Type: application/json

{
  "active": 0, 
  "autostart": 0
}



###
# @name deleteDomain
DELETE {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/domain/{{domainName}} HTTP/1.1
Content-Type: application/json

{}
