#
# Example VSCode rest client network HTTP calls
#

@baseUrl = http://nuke:8080

@driver = qemu
@hypervisor = system

@networkName = lab
# @networkUUID = 
# <uuid>{{networkUUID}}</uuid>
@networkPath = /lab/


###
# @name getAllNetworks
GET {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network HTTP/1.1
Content-Type: application/json

{}



###
# @name createNetwork
POST {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network HTTP/1.1
Content-Type: application/xml

<network type="dir">
  <name>{{networkName}}</name>
  <capacity unit="bytes">4306780815</capacity>
  <allocation unit="bytes">237457858</allocation>
  <available unit="bytes">4069322956</available>
  <source>
  </source>
  <target>
    <path>{{networkPath}}</path>
    <permissions>
      <mode>0755</mode>
      <owner>-1</owner>
      <group>-1</group>
    </permissions>
  </target>
</network>



###
# @name getNetwork
GET {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network/{{networkName}} HTTP/1.1
Content-Type: application/json

{}



###
# @name activateNetwork
PUT {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network/{{networkName}} HTTP/1.1
Content-Type: application/json

{
  "active": 1, 
  "autostart": 1
}



###
# @name deactivateNetwork
PUT {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network/{{networkName}} HTTP/1.1
Content-Type: application/json

{
  "active": 0, 
  "autostart": 0
}



###
# @name deleteNetwork
DELETE {{baseUrl}}/api/v1.0/{{driver}}/{{hypervisor}}/network/{{networkName}} HTTP/1.1
Content-Type: application/json

{}
